//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("IVSoftware.Portable.SQLiteMarkdown")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023-2025 IVSoftware LLC")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(("Lightweight, cross-platform expression-to-SQL parser with intuitive syntax. Suppo" +
    "rts query-then-filter workflows where external data can come from any source, wi" +
    "th in-memory filtering powered by SQLite. Features atomic quoted phrases and tag" +
    "-based terms."))]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.0.0-alpha31+294791d3b3fb3d3f3a34aa9ecd4857fd75a95204")]
[assembly: System.Reflection.AssemblyProductAttribute("IVSoftware.Portable.SQLiteMarkdown")]
[assembly: System.Reflection.AssemblyTitleAttribute("IVSoftware.Portable.SQLiteMarkdown")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/IVSoftware/IVSoftware.Portable.SQLiteMarkdown.git")]

// Generated by the MSBuild WriteCodeFragment class.

